### ISSUE TITLE
Déploiement auto avec Travis

### ISSUE THREAD

**Issue by gaelfoppolo** [romainlebreton/ProgWeb-ClientRiche#4]
Cela permettrait de déployer automatiquement gh-pages sur le github.io. Travis est un outil d'intégration continue. Voilà le tutoriel si intéressé : https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by romainlebreton** [comment]
Merci pour le lien mais je ne suis pas sûr que cela s'applique ici. En effet, dès que je pousse sur github, le site met à jour automatiquement le gh-pages sur le github.io...
